// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick3D_Effects();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick3D_Effects)

class QtQuick3DEffectPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick3DEffectPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick3D_Effects;
        Q_UNUSED(registration)
    }
};



#include "qtquick3deffectplugin_QtQuick3DEffectPlugin.moc"
