// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtLocation();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtLocation)

class QtLocationDeclarativeModule : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtLocationDeclarativeModule(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtLocation;
        Q_UNUSED(registration)
    }
};



#include "declarative_location_QtLocationDeclarativeModule.moc"
