// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Qt_labs_animation();
Q_GHS_KEEP_REFERENCE(qml_register_types_Qt_labs_animation)

class QtLabsAnimationPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtLabsAnimationPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Qt_labs_animation;
        Q_UNUSED(registration)
    }
};



#include "labsanimationplugin_QtLabsAnimationPlugin.moc"
