// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtCore();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtCore)

class QtQmlCorePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQmlCorePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtCore;
        Q_UNUSED(registration)
    }
};



#include "qtqmlcoreplugin_QtQmlCorePlugin.moc"
