// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtSensors();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtSensors)

class QtSensorsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtSensorsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtSensors;
        Q_UNUSED(registration)
    }
};



#include "SensorsQuickplugin_QtSensorsPlugin.moc"
