// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_VirtualKeyboard();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_VirtualKeyboard)

class QtQuick_VirtualKeyboardPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_VirtualKeyboardPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_VirtualKeyboard;
        Q_UNUSED(registration)
    }
};



#include "qtvkbplugin_QtQuick_VirtualKeyboardPlugin.moc"
