// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtWebChannel();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtWebChannel)

class QtWebChannelPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtWebChannelPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtWebChannel;
        Q_UNUSED(registration)
    }
};



#include "WebChannelQuickplugin_QtWebChannelPlugin.moc"
