// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQml_Models();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQml_Models)

class QtQmlModelsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQmlModelsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQml_Models;
        Q_UNUSED(registration)
    }
};



#include "modelsplugin_QtQmlModelsPlugin.moc"
