// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtCharts();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtCharts)

class QtChartsQml2Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtChartsQml2Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtCharts;
        Q_UNUSED(registration)
    }
};



#include "qtchartsqml2_QtChartsQml2Plugin.moc"
