// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Qt_labs_wavefrontmesh();
Q_GHS_KEEP_REFERENCE(qml_register_types_Qt_labs_wavefrontmesh)

class QmlWavefrontMeshPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QmlWavefrontMeshPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Qt_labs_wavefrontmesh;
        Q_UNUSED(registration)
    }
};



#include "qmlwavefrontmeshplugin_QmlWavefrontMeshPlugin.moc"
