// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_Controls_iOS_impl();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_Controls_iOS_impl)

class QtQuick_Controls_iOS_implPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_Controls_iOS_implPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_Controls_iOS_impl;
        Q_UNUSED(registration)
    }
};



#include "qtquickcontrols2iosstyleimplplugin_QtQuick_Controls_iOS_implPlugin.moc"
