list(APPEND known_libs AVFOUNDATION)
set(QMAKE_LIBS_AVFOUNDATION_DEBUG "-framework;AVFoundation")
set(QMAKE_LIBDIR_AVFOUNDATION_DEBUG "")
set(QMAKE_INCDIR_AVFOUNDATION_DEBUG "")
set(QMAKE_DEFINES_AVFOUNDATION_DEBUG "")
list(APPEND known_libs FFMPEG)
set(QMAKE_LIBS_FFMPEG_DEBUG "/usr/local/lib/libswscale.dylib;libswscale.dylib;/usr/local/lib/libswresample.dylib;libswresample.dylib;/usr/local/lib/libavdevice.dylib;libavdevice.dylib;/usr/local/lib/libavutil.dylib;libavutil.dylib;/usr/local/lib/libavformat.dylib;libavformat.dylib;/usr/local/lib/libavcodec.dylib;libavcodec.dylib")
set(QMAKE_LIBDIR_FFMPEG_DEBUG "/usr/local/lib")
set(QMAKE_INCDIR_FFMPEG_DEBUG "/usr/local/include")
set(QMAKE_DEFINES_FFMPEG_DEBUG "")
