// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_Controls_Fusion_impl();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_Controls_Fusion_impl)

class QtQuickControls2FusionStyleImplPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickControls2FusionStyleImplPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_Controls_Fusion_impl;
        Q_UNUSED(registration)
    }
};



#include "qtquickcontrols2fusionstyleimplplugin_QtQuickControls2FusionStyleImplPlugin.moc"
