// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_VirtualKeyboard_Plugins_Pinyin();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_VirtualKeyboard_Plugins_Pinyin)

class QtQuick_VirtualKeyboard_Plugins_PinyinPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_VirtualKeyboard_Plugins_PinyinPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_VirtualKeyboard_Plugins_Pinyin;
        Q_UNUSED(registration)
    }
};



#include "qtvkbpinyinplugin_QtQuick_VirtualKeyboard_Plugins_PinyinPlugin.moc"
