// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_Timeline();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_Timeline)

class QtQuickTimelinePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickTimelinePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_Timeline;
        Q_UNUSED(registration)
    }
};



#include "qtquicktimelineplugin_QtQuickTimelinePlugin.moc"
