// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_VirtualKeyboard_Plugins_Hangul();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_VirtualKeyboard_Plugins_Hangul)

class QtQuick_VirtualKeyboard_Plugins_HangulPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_VirtualKeyboard_Plugins_HangulPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_VirtualKeyboard_Plugins_Hangul;
        Q_UNUSED(registration)
    }
};



#include "qtvkbhangulplugin_QtQuick_VirtualKeyboard_Plugins_HangulPlugin.moc"
