// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_Controls_Basic_impl();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_Controls_Basic_impl)

class QtQuickControls2BasicStyleImplPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickControls2BasicStyleImplPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_Controls_Basic_impl;
        Q_UNUSED(registration)
    }
};



#include "qtquickcontrols2basicstyleimplplugin_QtQuickControls2BasicStyleImplPlugin.moc"
