// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_Dialogs_quickimpl();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_Dialogs_quickimpl)

class QtQuickDialogs2QuickImplPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuickDialogs2QuickImplPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_Dialogs_quickimpl;
        Q_UNUSED(registration)
    }
};



#include "qtquickdialogs2quickimplplugin_QtQuickDialogs2QuickImplPlugin.moc"
