# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::Quick3DParticleEffects Qt6::Quick3DParticleEffectsPrivate)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::Quick3DParticleEffects
add_library(Qt6::Quick3DParticleEffects SHARED IMPORTED)

set_target_properties(Qt6::Quick3DParticleEffects PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_QUICK3DPARTICLEEFFECTS_LIB"
  INTERFACE_COMPILE_OPTIONS "-fPIC"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;Qt6::Gui;Qt6::Qml;Qt6::Quick;Qt6::Quick3DRuntimeRender;Qt6::Quick3DAssetImport;Qt6::Quick3D;Qt6::Quick3DParticles"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtquick3d/src/quick3dparticleeffects/meta_types/qt6quick3dparticleeffects_debug_metatypes.json>"
  _qt_config_module_name "quick3dparticleeffects"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "OFF"
  _qt_module_interface_name "Quick3DParticleEffects"
  _qt_package_name "Qt6Quick3DParticleEffects"
  _qt_package_version "6.7.0"
  _qt_private_module_target_name "Quick3DParticleEffectsPrivate"
  _qt_qml_module_installed_plugin_target "Qt6::qtquick3dparticleeffectsplugin"
  _qt_qml_module_plugin_target "qtquick3dparticleeffectsplugin"
)

# Create imported target Qt6::Quick3DParticleEffectsPrivate
add_library(Qt6::Quick3DParticleEffectsPrivate INTERFACE IMPORTED)

set_target_properties(Qt6::Quick3DParticleEffectsPrivate PROPERTIES
  INTERFACE_LINK_LIBRARIES "Qt6::Quick3DParticleEffects"
  _qt_config_module_name "quick3dparticleeffects_private"
  _qt_is_private_module "TRUE"
  _qt_package_name "Qt6Quick3DParticleEffects"
  _qt_package_version "6.7.0"
  _qt_public_module_target_name "Quick3DParticleEffects"
)

# Import target "Qt6::Quick3DParticleEffects" for configuration "Debug"
set_property(TARGET Qt6::Quick3DParticleEffects APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::Quick3DParticleEffects PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/lib/libQt6Quick3DParticleEffects_debug.6.7.0.dylib"
  IMPORTED_SONAME_DEBUG "@rpath/libQt6Quick3DParticleEffects_debug.6.dylib"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "Qt6::Core" "Qt6::Gui" "Qt6::Qml" "Qt6::Quick" "Qt6::Quick3DRuntimeRender" "Qt6::Quick3DAssetImport" "Qt6::Quick3D" "Qt6::Quick3DParticles" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
