# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::qmlcachegen Qt6::qmldom Qt6::qmllint Qt6::qmltc Qt6::qmltyperegistrar Qt6::qmlimportscanner Qt6::qmlformat Qt6::qmlprofiler Qt6::qmltime Qt6::qmlplugindump Qt6::qmltestrunner Qt6::qmljsrootgen)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::qmlcachegen
add_executable(Qt6::qmlcachegen IMPORTED)

set_target_properties(Qt6::qmlcachegen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmldom
add_executable(Qt6::qmldom IMPORTED)

set_target_properties(Qt6::qmldom PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmllint
add_executable(Qt6::qmllint IMPORTED)

set_target_properties(Qt6::qmllint PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmltc
add_executable(Qt6::qmltc IMPORTED)

set_target_properties(Qt6::qmltc PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmltyperegistrar
add_executable(Qt6::qmltyperegistrar IMPORTED)

set_target_properties(Qt6::qmltyperegistrar PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmlimportscanner
add_executable(Qt6::qmlimportscanner IMPORTED)

set_target_properties(Qt6::qmlimportscanner PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmlformat
add_executable(Qt6::qmlformat IMPORTED)

set_target_properties(Qt6::qmlformat PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmlprofiler
add_executable(Qt6::qmlprofiler IMPORTED)

set_target_properties(Qt6::qmlprofiler PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmltime
add_executable(Qt6::qmltime IMPORTED)

set_target_properties(Qt6::qmltime PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtdeclarative/tools/qmltime/meta_types/qt6qmltime_debug_metatypes.json>"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmlplugindump
add_executable(Qt6::qmlplugindump IMPORTED)

set_target_properties(Qt6::qmlplugindump PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmltestrunner
add_executable(Qt6::qmltestrunner IMPORTED)

set_target_properties(Qt6::qmltestrunner PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Create imported target Qt6::qmljsrootgen
add_executable(Qt6::qmljsrootgen IMPORTED)

set_target_properties(Qt6::qmljsrootgen PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_QT_MAJOR_VERSION "6"
  _qt_package_version "6.7.0"
)

# Import target "Qt6::qmlcachegen" for configuration "Debug"
set_property(TARGET Qt6::qmlcachegen APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmlcachegen PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/libexec/qmlcachegen"
  )

# Import target "Qt6::qmldom" for configuration "Debug"
set_property(TARGET Qt6::qmldom APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmldom PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmldom"
  )

# Import target "Qt6::qmllint" for configuration "Debug"
set_property(TARGET Qt6::qmllint APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmllint PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmllint"
  )

# Import target "Qt6::qmltc" for configuration "Debug"
set_property(TARGET Qt6::qmltc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmltc PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmltc"
  )

# Import target "Qt6::qmltyperegistrar" for configuration "Debug"
set_property(TARGET Qt6::qmltyperegistrar APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmltyperegistrar PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/libexec/qmltyperegistrar"
  )

# Import target "Qt6::qmlimportscanner" for configuration "Debug"
set_property(TARGET Qt6::qmlimportscanner APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmlimportscanner PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/libexec/qmlimportscanner"
  )

# Import target "Qt6::qmlformat" for configuration "Debug"
set_property(TARGET Qt6::qmlformat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmlformat PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmlformat"
  )

# Import target "Qt6::qmlprofiler" for configuration "Debug"
set_property(TARGET Qt6::qmlprofiler APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmlprofiler PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmlprofiler"
  )

# Import target "Qt6::qmltime" for configuration "Debug"
set_property(TARGET Qt6::qmltime APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmltime PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmltime"
  )

# Import target "Qt6::qmlplugindump" for configuration "Debug"
set_property(TARGET Qt6::qmlplugindump APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmlplugindump PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmlplugindump"
  )

# Import target "Qt6::qmltestrunner" for configuration "Debug"
set_property(TARGET Qt6::qmltestrunner APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmltestrunner PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/bin/qmltestrunner"
  )

# Import target "Qt6::qmljsrootgen" for configuration "Debug"
set_property(TARGET Qt6::qmljsrootgen APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Qt6::qmljsrootgen PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/johanravnandersen/Desktop/Universitet/Software/Projects-skeleton/PhotoshopLite/build_Qt5/qtbase/libexec/qmljsrootgen"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
