// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtOpcUa();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtOpcUa)

class QtOpcUaPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtOpcUaPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtOpcUa;
        Q_UNUSED(registration)
    }
};



#include "DeclarativeOpcuaplugin_QtOpcUaPlugin.moc"
