// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtTextToSpeech();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtTextToSpeech)

class QtTextToSpeechPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtTextToSpeechPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtTextToSpeech;
        Q_UNUSED(registration)
    }
};



#include "TextToSpeechQml_QtTextToSpeechPlugin.moc"
