// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick3D_AssetUtils();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick3D_AssetUtils)

class QtQuick3DAssetUtilsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick3DAssetUtilsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick3D_AssetUtils;
        Q_UNUSED(registration)
    }
};



#include "qtquick3dassetutilsplugin_QtQuick3DAssetUtilsPlugin.moc"
