// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQml_Base();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQml_Base)

class QtQmlPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQmlPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQml_Base;
        Q_UNUSED(registration)
    }
};



#include "qmlplugin_QtQmlPlugin.moc"
