// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Qt_labs_lottieqt();
Q_GHS_KEEP_REFERENCE(qml_register_types_Qt_labs_lottieqt)

class BodymovinPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    BodymovinPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Qt_labs_lottieqt;
        Q_UNUSED(registration)
    }
};



#include "lottieqtplugin_BodymovinPlugin.moc"
