// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Qt5Compat_GraphicalEffects_private();
Q_GHS_KEEP_REFERENCE(qml_register_types_Qt5Compat_GraphicalEffects_private)

class QtGraphicalEffectsPrivatePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtGraphicalEffectsPrivatePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Qt5Compat_GraphicalEffects_private;
        Q_UNUSED(registration)
    }
};



#include "qtgraphicaleffectsprivate_QtGraphicalEffectsPrivatePlugin.moc"
