// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick_tooling();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick_tooling)

class QtQuick_toolingPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick_toolingPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick_tooling;
        Q_UNUSED(registration)
    }
};



#include "quicktooling_QtQuick_toolingPlugin.moc"
