// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQml_XmlListModel();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQml_XmlListModel)

class QtQmlXmlListModelPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQmlXmlListModelPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQml_XmlListModel;
        Q_UNUSED(registration)
    }
};



#include "qmlxmllistmodelplugin_QtQmlXmlListModelPlugin.moc"
