// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_QtQuick3D_Particles3D();
Q_GHS_KEEP_REFERENCE(qml_register_types_QtQuick3D_Particles3D)

class QtQuick3DParticles3DPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    QtQuick3DParticles3DPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_QtQuick3D_Particles3D;
        Q_UNUSED(registration)
    }
};



#include "qtquick3dparticles3dplugin_QtQuick3DParticles3DPlugin.moc"
